export const UPDATE_TEMPLATES_STATE = 'UPDATE_TEMPLATES_STATE'
export const UPDATE_TEMPLATE_STATE = 'UPDATE_TEMPLATE_STATE'

export const UPDATE_PAGINATION = 'UPDATE_PAGINATION'

export const UPDATE_QUERYSET_STATE = 'UPDATE_QUERYSET_STATE'
