export const UPDATE_TEMPLATES_STATE = 'UPDATE_TEMPLATES_STATE'
export const UPDATE_TEMPLATE_STATE = 'UPDATE_TEMPLATE_STATE'

export const UPDATE_APPS_STATE = 'UPDATE_APPS_STATE'
export const UPDATE_HOSTS_STATE = 'UPDATE_HOSTS_STATE'
export const UPDATE_HOST_STATE = 'UPDATE_HOST_STATE'
export const UPDATE_JOBS_STATE = 'UPDATE_JOBS_STATE'
export const UPDATE_APPBATCHS_STATE = 'UPDATE_APPBATCHS_STATE'
export const UPDATE_APPBATCH_STATE = 'UPDATE_APPBATCH_STATE'
export const UPDATE_UNHOSTS_STATE = 'UPDATE_UNHOSTS_STATE'
export const FETCH_AWXJOB_FAIL = 'FETCH_AWXJOB_FAIL'
export const FETCH_AWXJOB_SUCC = 'FETCH_AWXJOB_SUCC'
export const UPDATE_SYSTEMS_STATE = 'UPDATE_SYSTEMS_STATE'

export const UPDATE_PAGINATION = 'UPDATE_PAGINATION'

export const UPDATE_QUERYSET_STATE = 'UPDATE_QUERYSET_STATE'
